### ISSUE TITLE
variable for excluding pages from build

### ISSUE THREAD

**Issue by jonschlinkert** [assemble/assemble#122]
One way to accomplish this is using a `published` variable:

YAML front matter:

``` yaml

---
title: About
published: false

---
```

This file will be excluded from output.
