### ISSUE TITLE
variables for categories and tags

### ISSUE THREAD

**Issue by jonschlinkert** [assemble/assemble#123]
`page.categories` and `page.tags`. YAML front matter allows list-style or "arrays". 

Example:

``` yaml

---
title: Portfolio
tags: [one, two, three]
categories: 
  - one
  - two
  - three

---
```

the same in json

``` json
{
  "title": "Portfolio",
  "tags": [
    "one",
    "two",
    "three"
  ],
  "categories": [
    "one",
    "two",
    "three"
  ]
}
```
