### ISSUE TITLE
assemble:project:files is broken in latest update

### ISSUE THREAD

**Issue by conspirator** [assemble/assemble#128]
```
assemble:
      project:
        options:
          partials: "src/partials/*.hbs"
          layout: "src/templates/layout.hbs"
        files:
          "templates": ['src/views/**/*.hbs']
```

This generates `templates.html` instead of `/templates/*.html`.
