### ISSUE TITLE
Passing inline content to a partial?

### ISSUE THREAD

**Issue by lmartins** [assemble/assemble#173]
Is it possible to pass content to a partial right from the partial call?

Something similar to what was demonstrated for YAML front-matter:

```
alert:
  strong: Data for the alert partial.
  message: >
    You can specify data in the YAML front-matter as we're doing here, or in external JSON or YAML files, or inside the Assemble task in the Gruntfile.
content: src/content/links.md
```

But for content inside the views.
