### ISSUE TITLE
process handlebars templates in yaml front matter

### ISSUE THREAD

**Issue by jonschlinkert** [assemble/assemble#26]
This will allow partials and handlebars tags to be more flexible and DRY. The page title is a good example:

``` html
<h1>{{page.title}}</h1>
```

For which the yaml front matter is:

``` yaml

---
page:
  title: Hi! I'm the page title!

---
```

Now, if you are visiting a theme, you might want the name of the theme to be the page title, so you could change the template on every page, like this:

``` html
<h1>{{theme.name}}</h1>
```

and this:

``` yaml

---
page:
  title: 
theme:
  name: Bootstrap

---
```

But a better way to do it is to keep the template the same, like this:

``` html
<h1>{{page.title}}</h1>
```

and process templates in yaml front matter like this:

``` yaml

---
page:
  title: {{theme.name}}
theme:
  name: Bootstrap

---
```
