### ISSUE TITLE
add `mixins` property to options

### ISSUE THREAD

**Issue by jonschlinkert** [assemble/assemble#458]
Allow mixins to registered following the same conventions as helpers and plugins, so they can be used with config data. e.g.

``` js
options: {
  mixins: ['mixins/*.js']
}
```

Currently, with grunt a mixin can easily be registered in the Gruntfile, e.g

``` js
grunt.util._.mixin({
  hostname: function(str) {
    return url.parse(str).hostname;
  }
});
```

and then used anywhere in the config data (JSON, YAML, YAML front matter, etc):

``` yaml
url:
   public:     http://assemble.io/
   domain:   <%= _.hostname(site.url.public) %>
```

We'll need to implement this as an option so that existing projects can continue to use mixins with or without Grunt.
