### ISSUE TITLE
define config values in yaml front matter

### ISSUE THREAD

**Issue by jonschlinkert** [assemble/assemble#484]
Assemble can easily build things like robots.txt, sitemaps, etc. from a regular template (e.g. without the need for a helper), but I usually don't because I won't setup additional targets for a single file. it seems silly to do that. 

Both @hariadi and I have created plugins for these things, but using a plugin sometimes is just overkill.  

Ideally, we would be able to define `dest`, `ext` and maybe even options in YAML front matter, so that no additional config would be required for these things. 

For example, the `robots` template might look like this:

```yaml
---
layout: none
dest: ./robots.txt
---
# www.robotstxt.org/

# Allow crawling of all content
User-agent: *
Disallow:
Sitemap: {{ site.homepage }}/sitemap.xml
```
Assemble would use the `dest` property defined in the yaml front matter to dynamically update the config and build the file to `./robots.txt`.
