### ISSUE TITLE
How to load middleware in assemble v0.6.0

### ISSUE THREAD

**Issue by stefanwalther** [assemble/assemble#715]
Hi,

how can I load middleware in assemble v0.6.0, this doesn't work:

```js
assemble.middleware( ['assemble-middleware-drafts'] );
```

Thx in advance!
Regards
Stefan

**Comment by akileez** [comment]
I believe assemble.middleware-drafts is for version 0.5.0 which was never released. but you can achieve the same thing in v0.6.0 by putting draft: true in the yfm of the published page...

```yaml
---
name: Keith Williams
layout: tmplCore
slug: badges
navTitle: badges
draft: true
---
```
the page will not be published in this case
