### ISSUE TITLE
Lodash Templates/Variables not processed in YFM for .hbs files

### ISSUE THREAD

**Issue by avr** [assemble/assemble#758]
I'm trying to use Lodash templates/calls to set various context for my pages.

For example, I have the following:

```yaml
---
title: About
banner_type: image
section_nav_context: <%= default_nav.about.children %>
---
```

In my template, I'd hope to get the object represented by `default_nav.about.children` from `assemble.data`.  Instead, I just get a string of `<%= default_nav.about.children %>`.

Am I missing how YFM works/can parse this?  I'd like to do something like:

```handlebars
{{> "section_nav" section_nav_context}}
```

And in `section_nav.hbs` use the following:

```handlebars
{{#each section_nav_context }}
    <li><a href="{{this.url}}">{{this.title}}</a></li>
{{/each}}
```
